### ISSUE TITLE
METEOR MN2-2

### ISSUE THREAD

**Issue by pfranchini** [dbdexter-dev/meteor_decode#1]
I have understood it uses OQPSK demodulation, so cannot be decoded by this software.

**Comment by dbdexter-dev** [comment]
It looks like M2-2 not only uses a different modulation scheme, but also transmits data in a different format. And I haven't found a datasheet describing the new data format yet, so I'm afraid I won't be able to do much for now. If I find one, I'll try to support Meteor M2-2 as well.

**Comment by dbdexter-dev** [comment]
I've pushed an update on the 'devel' branch that supports the differential decoding required for M2-2 (-d flag). It's still not completely bug-free, but it should work fairly well.

**Comment by pfranchini** [comment]
Thanks for that, I am testing "Meteor-M2 LRPT demodulator v0.3-beta1" right now with some files I have created with the very same command I use for M2

`rtl_fm -M raw -f ${frequency}M -s ${sampling}k -g 48 -p 0.0 | sox -t raw -r ${sampling}k -c 2 -b 16 -e s - -t wav ${filename}.wav rate 96k`

so I am not entirely sure if are correctly recorded.

**Comment by dbdexter-dev** [comment]
M2 and M2-2 take up about the same bandwidth, so there is no significant difference between recording the newer satellite and the older one. So yes, the recordings you have should be decodable.

**Comment by hhrhhr** [comment]
@dbdexter-dev , great work!
With minor changes, I compiled the demodulator and decoder using MinGW-w64 for Windows and tested them on a previously saved raw IQ file. 

2019-07-19_10_32_M2_2_best.flac (458 Mb, OQPSK, symrate 72K) — https://yadi.sk/d/MDTNwV8AzayWiQ
This file taken from http://www.radioscanner.ru/forum/topic47659-127.html#msg1441079 and recoded to FLAC.

I added to the demodulator the ability to read standard input instead of regular files to load decoded FLAC files instead of huge WAVs, so the process looks something like this:
```
flac.exe -s -c -d rawIQ.flac | meteor_demod.exe -m oqpsk -B -R 1000 -
meteor_decode.exe -a 66,65,64 -d -q -s LRPT_YYYY_MM_DD-HH_MM.s
```

And here are the results obtained by the decoder and M2_LRPT_Decoder (v42, 2019.9.30.0042):
[![from_decoders_thumb](https://user-images.githubusercontent.com/966048/63026277-8fa6af80-beb3-11e9-8e0d-6717f85e9ddc.jpg)](https://imgur.com/a/W7cBLrB)

With default settings, meteor_decode gives a bit more errors and omissions on a weak and noisy signal. if you increase the options "fir-order" and "oversamp", then the errors become much less at the cost of increasing the time.

**Comment by cytrinox** [comment]
I've successfully decoded a MN2-2 signal (symrate: 80000) a few days ago, but with the MN2-2 pass today, meteor_decode (beta/devel branch) is unable to find any packets.

Demod with meteor_demod:

> ~/sdradio/src/meteor_demod_v3/src/meteor_demod -r 80000 -m oqpsk gqrx_20190824_133714_137900000_140000_fc.wav

Decode with meteor_decode:

> ~/sdradio/src/meteor_decode/src/meteor_decode -d  -s -a 66,65,64 LRPT_2019_08_24-17_05.s
```
LRPT decoder v0.2-beta2

Decoding started
0x03E1F31F rs=-1 
Decoding complete
Successfully decoded packets: 0/4105 ( 0.0%)
```


I've replayed the wav file with SDR# connected to LRPTDecoder and was able extract the three channels, so I'm sure there is data available.

All files available at: https://chaospixel.com/pub/rtlsdr/mn22/rec20190824/

Edit: I could process the *.s file from meteor_demod with LRPTDecoder, too. I'm 99% sure that it's a problem only in meteor_decode (or pebkac).

**Comment by benelsen** [comment]
Do you know when exactly you succeeded in decoding that M2-N2 pass the last time? 
Until a few days ago (2019-08-20 ~12:00 UTC) M2-N2 transmitted with a 72k rate. Since then I had no success and I believe the data structure is slightly different from what meteor_decode expects right now.

**Comment by cytrinox** [comment]
@benelsen not sure, I remember I've used meteor_demod with -s 80000 a few times and got good results with meteor_decode from the *.s file. IIRC it was on the same/next day as the old meteor switched to 137.1 MHz and the new used 137.9.

**Comment by dbdexter-dev** [comment]
I know I'm eons late on this, but I finally had enough time to sit down and implement 80k mode decoding the right way. Pretty much useless for now since M2-2 was bonked by a meteorite, but will probably come in handy after M2-3 launches later this year.
