### ISSUE TITLE
[Feature] Add progress indicator

### ISSUE THREAD

**Issue by the-gobleo-tinkerer** [dbdexter-dev/meteor_decode#8]
It would be nice to have a progress indicator to show how much of the input file we have processed so the user knows how long it will take. This already exists in `meteor_demod`, which shows both a percentage and the total and processed lengths of the input file.

**Comment by pfranchini** [comment]
It might need some option to enable it, otherwise piping the output into a text file might cause a mess

**Comment by the-gobleo-tinkerer** [comment]
Sorry for late reply @pfranchini. I do realise meteor_demod's progress indicator updates constantly, which would look ugly if saved into a file, however I don't think it is necessary to make the progress indicator optional in meteor_decode. The ncurses interface (the one with the constellation diagram) isn't supposed to be piped into a file anyway, and batch mode output should be fine if we just append the % progress to every output line (instead of having a constantly refreshing progress bar).

I'll try making some changes and hopefully make a PR for people to review.

**Comment by dbdexter-dev** [comment]
So I recently looked at the code I wrote here, and the tl;dr is: it's a mess. In fact, I stopped working on it a few weeks after M2-2 was launched because everything was an undebuggable soup.
I'm currently in the process of rewriting most of the codebase from scratch, once I've reached feature parity with meteor_decode I'll publish it.
While I'm at it, might as well add the progress indicator. Is the way [meteor_decoder](https://github.com/artlav/meteor_decoder) does it okay? Something like this: 
`pos=  542646 (  1.29%) ( 6,    0,53) sig= -239 rs=(-1,-1,-1,-1) A474CFE9`

**Comment by the-gobleo-tinkerer** [comment]
@dbdexter-dev Yes I'd say meteor_decoder (medet) displays all I want. Great to know there's been development going on!

One side note: medet's onboard time display is a lot more flickery than meteor_decode's (in the devel branch). I haven't looked into why but just saying it would be great if meteor_decode's display stays as stable and smooth as it is now :D

**Comment by dbdexter-dev** [comment]
Good news, I'm pretty sure I implemented all the features I wanted in the new decoder. [Here it is](https://github.com/dbdexter-dev/impact).
From my tests it performs better than both medet and meteor_decode on weak signals, so that's a nice bonus. Check it out whenever you want, and let me know if the status line needs further adjustments.

**Comment by the-gobleo-tinkerer** [comment]
Did some testing with a previous IQ recording and all seems to be working fine. Impact decoded a few more lines at the beginning and end where signal is bad, so looks like it is better with weak signals.

Impact showed a big speed improvement over meteor_decode so that's great. Decoding a 121 MB .s file on i7-8565U, 

Program | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Average | Variance
-- | -- | -- | -- | -- | -- | -- | --
meteor_decode | 76.43 | 75.04 | 76.24 | 75.02 | 74.49 | 75.44 | 0.57
impact | 15.09 | 14.12 | 13.99 | 14.22 | 14.96 | 14.48 | 0.21

(Numbers in seconds)

One thing I noticed is that the seq numbers shown by Impact are different from those shown by meteor_decode. With the same .s file, meteor_decode starts from seq = 6627 and wraps around at 16384, whereas Impact starts at seq = 11208874 and only reaches 11215184, without wrapping around.

**Comment by dbdexter-dev** [comment]
Good catch on the sequence numbers. That's because the data from the satellite is wrapped in multiple layers (a la OSI model), and Impact prints sequence numbers from a lower layer, which wraps around every 2^24 packets instead of 2^14.
I did it cause one packet at that lower layer is exactly 2048 bytes long, while a packet at the higher layer has a variable length. It made debugging easier, and I haven't found a reason to print the sequence numbers meteor_decode displays, as they both indicate the same thing (namely, that packets are being properly decoded).

Thanks for posting your results, they pretty much confirm the numbers I have from running impact on my laptop. Glad to see the same performance improvements on your machine too.

**Comment by the-gobleo-tinkerer** [comment]
@dbdexter-dev OK thanks for the explanation! Good to know, as long as it's not a bug I'm happy.

**Comment by pfranchini** [comment]
> Did some testing with a previous IQ recording and all seems to be working fine. Impact decoded a few more lines at the beginning and end where signal is bad, so looks like it is better with weak signals.

I confirm that.

**Comment by dbdexter-dev** [comment]
Good good, since things are working well I've just merged the code into meteor_decode. Closing since this feature is now implemented on master.
